### ISSUE TITLE
Need testcases

### ISSUE THREAD

**Issue by Kflash** [ugma/ugma#1]
Need to add testcases

**Comment by Kflash** [comment]
We also need to add major qUnit tests regarding shadow DOM and shadow Roots. And make sure ugma works against it as it should. First easy test could be to test the computeStyle() function and see if it's picking up the styles in the shadow DOM.

**Comment by Kflash** [comment]
@mehranhatami nice if you also run tests on isXML() function and checks if it can find XML docs, SVG docs and HTML docs. I hope it work as expected :)

**Comment by mehranhatami** [comment]
@Kflash the initial decision is the test engine. Do you prefer [QUnit](http://qunitjs.com) over [Mocha](http://mochajs.org)? From my perspective the only preferable feature with QUnit is its simplicity, but IMHO Mocha has a lot more to offer when it is used along with [chaijs](http://chaijs.com).

**Comment by Kflash** [comment]
@mehranhatami It's up to you as long as this is not breaking the AMD structure we got here. Anyway. I think you are more familiar with Mocha, so switch to that. Agree? Better to have things running in background then html pages to click on as you can do with qUnit. But your choise

**Comment by Kflash** [comment]
@mehranhatami Let me know when you email are working again. I'm back to work again on the  **Ugmati Animation Framework** now.

**Comment by Kflash** [comment]
@mehranhatami Regarding test cases. Now when I do a few changes in ugma you can see in the **commit log** all my changes. I write detailed there what I did. Hope that help you better in the future.

**Comment by Kflash** [comment]
@mehranhatami I took a marathon race now and I hope I killed all bugs so you take it from here. Awaiting  test cases now. Just await selector testing. Need to re factor a little... Let me know when changed to Mocha and chaijs.

**Comment by mehranhatami** [comment]
@Kflash thanks, now I could setup the testing environment.

**Comment by Kflash** [comment]
@mehranhatami Just fixed all the CSS query problems and issues. Everything now works like a charm. So when can I expect to see the first test cases??

**Comment by Kflash** [comment]
@mehranhatami  Any progress with the test cases? It has gone 6 days now. Ugma are now optimized and I need test results before I do anything else. If no action taken in the next 24 hours, I will re-assign myself on this task.

**Comment by Kflash** [comment]
@mehranhatami What is your progress on this case?

**Comment by mehranhatami** [comment]
Last night I found issues with Mocha on Karma and I started digging through
QUnit to see if it makes sense to use it instead. I won't have much problem
to rewrite the tests because the signature is very similar.

**Comment by Kflash** [comment]
@mehranhatami Ok. But a very important question here is before you can test this at all. Do you understand how ugma works? I questioned you in a couple of un-replied emails.

Anyway. We will need to test for SVG and XML later on as well. Much later.

**Comment by mehranhatami** [comment]
@KFlash to be honest, at the moment I can not say I'm completely following
the whole idea or I totally understand it. I know what it is all about, but
I think I still need a guideline to see the big picture.

**Comment by Kflash** [comment]
@mehranhatami ok. I will be back home later on today and write a long email. Let me know if you receive my emails. Else Skype?

**Comment by Kflash** [comment]
@mehranhatami I sent you a guideline on email. Study it before more test
cases. Let me know your feedback

**Comment by Kflash** [comment]
@mehranhatami Any progress on this case?

**Comment by Kflash** [comment]
@mehranhatami Waiting for the test cases . Any progress?

**Comment by Kflash** [comment]
@mehranhatami are you finish now?

**Comment by mehranhatami** [comment]
@KFlash tests are still in progress, all getting rewritten from scratch,
just to make projects more stable. All will be uploaded soon.

**Comment by mehranhatami** [comment]
@KFlash hope it is worth working on this, but the tests will be there to
protect the code.

**Comment by Kflash** [comment]
@mehranhatami well. I thought we was agree to earn money with it. Should be
worth it then

**Comment by Kflash** [comment]
@mehranhatami  Any progress on the test cases?

**Comment by Kflash** [comment]
@mehranhatami  Don't forget to run tests for object setters as well. I just added that method now.
