### ISSUE TITLE
IE8 support?

### ISSUE THREAD

**Issue by Kflash** [ugma/ugma#11]
@mehranhatami Do we need to support IE8?

**Comment by mehranhatami** [comment]
@KFlash from my angle it doesn't seem to be necessary, but it is up to you.
Just consider the fact that adding IE8 support has less value than
providing the state of the art solutions.

**Comment by Kflash** [comment]
@mehranhatami My concern is that Asia people seem to prefer Windows XP -
IE8. But from januar 2016 all support from Microsoft end when it come to
IE7/8. And AngularJS seems to have dropped it from v. 1.2.x. But this days
it's very easy to upgrade a browser, and companies have only a few months
left to migrate. So yes, I think we skip it.

Can you delete the compat branch?

**Comment by Kflash** [comment]
@mehranhatami and close tihis issue?
