### ISSUE TITLE
Ugma tests

### ISSUE THREAD

**Issue by Kflash** [ugma/ugma#14]
@mehranhatami  I started to look into qUinit now and the test cases because it seems you are back in your own world. 

So for now I assigned myself on this task - just re-assign yourself if you want to.

qUnit is a totaly new world for me, and the syntax I have to learn. But I learn fast :+1: 

So you know. There was a issue in the previous test case setup, and PhantomJS stopped working because of missing qUnit.start().

This is the case now, and my progress:

* updated qUnit to new version - 1.16 -> 1.17.1
* updated some grunt files
* re-factored travis
* Old test case thrown out the window
* Re-factored the test cases
* Made it modular so we just now have core **module** and **css module**
* Running 11 assertions just now - 10 for the core module and 1 for the css module
* Cleaned up the CSS mess, so they are all hidden now, but still working. Not on top of page anymore.
* async load of each test case / module

Work that remains:

- figure out how to avoid the function scoping you had added before

@mehranhatami You take it from here?

**Comment by Kflash** [comment]
@mehranhatami I do progress. Just got rid of the function scoping and your start() and stop() every where. 

ugma are attached now into the page with document.write method, and loaded as a requirment for requireJS.

It seems for me what is left now is to write all test cases. Can you verify this?

**Comment by Kflash** [comment]
@mehranhatami  Quick info. qUnit have several options as you may know. If you run my test case setup locale you will see that under the ** Ugma Test Suite** banner, that they are there.

They are all working except **Load with AMD**. It's not a problem to get it work too, but because of the fact that **ugma** don't have a AMD loader method in the intro.js file, it will not work.

The future plans for **ugma** is to use the ES6 specs, and no AMD in the same way as you know from jQuery.

So for me that is not important to get it working, IF you need it, add the needed code in top of the intro.js file in **/src/export folder**.

All the settigns for this to work are already done in the **/tests/ugma.js** file.

**Comment by Kflash** [comment]
@mehranhatami Latest update on this is that I have spent 4 hours to set things up and write test cases ! Very tired in my brain, but I keep going to add back all the test cases.

More test cases will be added as soon as the modules are there.

**Comment by Kflash** [comment]
@mehranhatami  You take it from here as you have better knowledge about it. I just got it to work again, and putting back my test cases!

**Comment by Kflash** [comment]
@mehranhatami You fix the rest now. OK? The test cases are added back again, and Travis are working again without PhantomJS issue. Happy or not?

Feedback needed!!

**Comment by Kflash** [comment]
@mehranhatami  Waiting for you to finish test cases now. I added 238 of them, but didn't take the time to figure out how to deal with callbacks. Callbacks as in a event handler etc.

**Comment by mehranhatami** [comment]
@Kflash today, hopefully is my final day on tests, I have got two different
options, first is dealing with AMD and if didn't work, second option, I'll
start coming up with a workaround to tackle this issue once for good.

**Comment by Kflash** [comment]
@mehranhatami I see. Btw. did you check how I did things in my "fixes"?

What actually are your AMD problem? If you read this thread, you can get
AMD to work as you see, if you do a litle change as I described.

For me in the temporary fixes I did, I uses modules etc. Just run my test
cases in master repo

**Comment by Kflash** [comment]
@mehranhatami The temporary fixes I did with the test cases when PhantomJS broke down :-1:  Was to re-factor the whole thing and now it works and act just like jQuery test case suit.

With modules!

**Comment by Kflash** [comment]
@mehranhatami  I let you handle everything from here, and write all missing test cases.

You now have:

* 292 assertions
* 24 modules

**Comment by Kflash** [comment]
@mehranhatami you got over 320 tests now fully working and 27 modules.

Everything works in the same way as jquery test cases.

If you run index.html you see the test environment. On right side on the
top you choose modules or all tests.

For AMD see my previous comment.

Need to find out how to test events.

Waiting for finale result. ..

**Comment by Kflash** [comment]
@mehranhatami Why didn't you finish your task?

**Comment by Kflash** [comment]
@mehranhatami  I added now around 370 assiations. The code is not breaking. Everything works fine. You find the testcases in **/test/modules**.

Any idea how to fix test cases for events? I did manage to solve a few test cases for manipulation.js.

When are you done with this task?

**Comment by Kflash** [comment]
@mehranhatami finish with the test cases?

**Comment by Kflash** [comment]
@mehranhatami Waiting for test cases to be done. Any progress the last 34 days?
