### ISSUE TITLE
Performance and code size

### ISSUE THREAD

**Issue by Kflash** [ugma/ugma#21]
**ugma** tries it's best to be as small, compact and fast as possible. This goals are archived with avoiding re-flows and function overloading as we can find in other libraries such as **jQuery**.

**ugma** are also optimized for mobiles, and will have the same performance there as on a desktop computer.

As an example I can mention I had a interesting reading in one of the jQuery issue tickets:

https://github.com/jquery/jquery.com/issues/88

Scroll down to the post by Paul Irish.

The issue are about - show(), hide() and toggle().

The interesting stuff here is that it takes 700.2ms to perform the mentioned function, and CPU usage are 1.89%.

On a mobile device this would consume a lot of battery!!

Then I tried to re-create a similar scenario for **ugma** and what ever I did, the CPU usage wouln't go higher then 0.05%.

There is a big difference betwen 1.89% and 0.05%.

Average performance was 4.2ms.

Again! A huge difference between 700.2ms and 4.2ms.

What had bad performance was the browser itself - 112.3ms - but that is out of the scope of ugma.

**Note!** This was just a simple example, and also note that you can archive fadeToggle() and other CSS related animation as well with the same methods, and the performance would still be the same.

Ugma also isolate browser related code to the browser where the issues occur.

Another great example.

Take a look at the same post as linked to above.  See comment from **timmywill** where i mention that the biggest bottleneck are the native method **getPropertyValue**

So, if we look at the jQuery code related to this, we will see that this method are used not only for IE9, but everywhere.

Have a look at **ugma** code: 

https://github.com/ugma/ugma/blob/master/src/css.js#L88

As we can read out from this line is that **getPropertyValue** only will be used **IF** the browser are **Internet Explorer 9 AND** the property are **filter**.

Doing similar things through the whole code base let us gain better performance all over, and litle slower performance where it's needed. But the slower performance are not ugma's fault. It's the browsers!

@mehranhatami Anything to fill in on this?

**Comment by paulirish** [comment]
your use of getComputedStyle will have the exact same effect.

**Comment by paulirish** [comment]
It was a problem for jQuery because you shouldnt have to get any computed style when you ask to hide() something.

**Comment by Kflash** [comment]
Ok. So this is still a bottleneck. I used to cache the computed values on
the element itself so I only touched the DOM once. But dropped the code
there.

I will investigate this..

your use of getComputedStyle will have the exact same effect.

—
Reply to this email directly or view it on GitHub
<https://github.com/ugma/ugma/issues/21#issuecomment-73415310>.

**Comment by Kflash** [comment]
Re-factored some of the code code now, and seems like the animation running smoother. ComputedStyle are no longer used, and only cached where it needed.
