### ISSUE TITLE
A+ promises

### ISSUE THREAD

**Issue by Kflash** [ugma/ugma#28]
@mehranhatami Ugma now got it's own Promise library based on the ES6 Promises, and it support the A+ standards. Can you test the code and add / remove functions if needed.

And try to optimize?

**Comment by Kflash** [comment]
@mehranhatami Can you also try to get rid of so many try / catch you can.

**Comment by Kflash** [comment]
@mehranhatami Can you continue the development here?

**Comment by Kflash** [comment]
@mehranhatami I added a few test cases for the ugma.Promise() now. And they are all green. resolve(), reject() etc. I also tested this now against A+ and also green.

But you need to add a few more test case.

**Comment by mehranhatami** [comment]
@Kflash all I think is needed is just to pass the A+ promises unit tests,
I'll take a look to see if it passes the latest tests.

**Comment by Kflash** [comment]
@mehranhatami All I did was following descriptions lookated here: https://promisesaplus.com/

**Comment by Kflash** [comment]
@mehranhatami Did you do your tasks here? I re-factored ugma.Promise a little now. Changed how the thenables are working.

How long time before you have done this?

**Comment by Kflash** [comment]
@mehranhatami I close this now. I re-factored ugma so it used native browser A+ Promise and a pollyfill for IE.
