### ISSUE TITLE
DOM Level 4 changes

### ISSUE THREAD

**Issue by Kflash** [ugma/ugma#4]
Because of the upcomming DOM Level 4, ugma now follows some names and methods from DL4. This includes some major changes in ugma.

Find[All] ->  query[All]

Find[All] are part of the DOM Level 2, but the new changes reflects the new DOM Level 4. And this changes adds a new class called Elements, which extends Array.prototype so you can do things like document.queryAll('.classname').map(fn).

Same is possible TODAY with ugma.

@mehranhatami Can you think about a solution to extend the subscription to also include DOM node observation?

**Comment by Kflash** [comment]
@mehranhatami Any progress on this?

**Comment by Kflash** [comment]
@mehranhatami  Did you come to a conclusion on this?

**Comment by mehranhatami** [comment]
@KFlash I need some time to read the whole spec and your explanation.

@mehranhatami <https://github.com/mehranhatami> Did you come to a
conclusion on this?

—
Reply to this email directly or view it on GitHub
<https://github.com/ugma/ugma/issues/4#issuecomment-70161501>.

**Comment by Kflash** [comment]
@mehranhatami In the DOM L4 specs that is still a draft, only important to read query[All] and what they say about a **live** Nodelist and the Element class.  

And also **:scope** selector support for query[All] is important.

I assume you have read my 3 tutorials now sent on email, and the follow up??

If you did, and you learned something, you know about our subscription. My idea was just to extend it in that way we create a internal registry method that keep track on each DOM element created and inserted during the lifetime of the webpage before new pageload (with pageload it will be zero out anywya).

With this registry we could observe each node, and if a event handler are attached or they are removed or something else going on with this DOM nodes, we could do the same as for attributes.

Just my thoughts!!

Waiting for your conlusion after reading through everything!!
