### ISSUE TITLE
Testcases broke Travis!

### ISSUE THREAD

**Issue by Kflash** [ugma/ugma#5]
@mehranhatami  Your test cases seems to break Travis. Can you fix this? Everything was working just fine before the test cases was added.

**Comment by Kflash** [comment]
@mehranhatami I grayed out the test cases for now, and Travis is back to normal. Waiting for your fix on this one.

**Comment by mehranhatami** [comment]
@Kflash I added a new branch to fix the QUnit testing scenario.

**Comment by Kflash** [comment]
@mehranhatami if you need to change something in code . Don't swallow with
try /catch. Use the invoke () method. I fixed element method so it's reject
windows and put the rest in Dark DOM if not nodetype 1

**Comment by mehranhatami** [comment]
@KFlash it seems interesting, like to see how it works.

**Comment by Kflash** [comment]
@mehranhatami With your test approach so far I don't think this will work. I wasted some time to figure it out, but still broken. When will this be fixed??

**Comment by mehranhatami** [comment]
@KFlash to fix it we should first fix Ugma's dependency tree. It probably
takes couple of days, but I will push my everyday code, so that you could
see the way it's getting fixed.

**Comment by Kflash** [comment]
@mehranhatami  What is wrong with the dependency tree? If you compare with jQuery, the tree is identical in the way the build are set up. Look at jquery.js and core.js. Equal! Only main difference here is that ugma are **not** and **will never be** and **shall never be** a function.

Let us compare with **AngularJS**. https://github.com/angular/angular.js/blob/v1.4.0-beta.0/src/loader.js#L21

As you see **angular** is not a function either.

**Comment by Kflash** [comment]
@mehranhatami  I'm confused! I spend some time now to write a few simple test cases, and Travis is not crying. Green light on them all. Can you explain this??

**Comment by Kflash** [comment]
@mehranhatami I'm not sure about how you put up this test case. It is not Jasmine that you have used, so what you used? Anyways. You handle this.

**Comment by mehranhatami** [comment]
@KFlash as you also mentioned, it doesn't have ANYTHING to do with the Ugma
being a function, ANYTHING AT ALL. All the point is the dependency tree.
For instance each define black should return something. And you could only
use those modules that are written in a well-defined AMD style. Having to
return something as the module object, is one of the rules, not having
circular references is the other one, and eventually not using globals. If
you for instance use globals the dist build could be working as expected,
but the testing system can not tolerate it. One simple way is just using
the dist/ugma.js file for testing which is not a good practice here. Why?
Because one of the main reasons for using the AMD coding style in ugma,
similar to jQuery, is having each piece of the system tested separately. So
as said if we could fix the dependency tree in a way that RequireJS could
load each module separately, the main goal of the mission is achieved.

**Comment by mehranhatami** [comment]
@KFlash one of the issues for instance could be in src/ugma.js file. We
have a code block like:

    window.ugma = ugma;

Whereas there is no variable named ugma in the scope, which could easily
get fixed by:

    window.ugma = core;

Because if you take a look at the core module the last statement is:

    return ugma;

Hope it makes sense.

**Comment by mehranhatami** [comment]
@KFlash one of the issues for instance could be in src/ugma.js file. We
have a code block like:
```javascript
window.ugma = ugma;
```
Whereas there is no variable named ugma in the scope, which could easily
get fixed by:
```javascript
window.ugma = core;
```
Because if you take a look at the core module the last statement is:
```javascript
return ugma;
```
Hope it makes sense.

**Comment by Kflash** [comment]
@mehranhatami what you pointing out there is equal to jquery. See jquery.js
and core.js.

But try!!

You can modify the code but note in the source I'm strict with comments.

So if you modify for testing your comment start like:

// Mehran. Support: testing purpose

**Comment by Kflash** [comment]
@mehranhatami I notice your testing setup are vert different too from
jquery and they using AMD style. Maybe try to be equal

**Comment by mehranhatami** [comment]
So let's make it clear, this is the jQuery's alternative:
```javascript
define([
	"./core",
	"./selector",
       //the rest of dependencies
], function( jQuery ) {
  return (window.jQuery = window.$ = jQuery);
});
```
As you see in this code the AMD function is like: `function( jQuery ) {}` which if you focus you will see that the `jQuery` is the name of the only parameter not 'core', whereas in ugma we have:
```javascript
define([
  './core',
  './document',
  //the rest of dependencies
], function(  core /*the rest of args*/) {
  return (window.ugma = ugma);
});
```
as you see the name of the first param here is `core` not 'ugma' and in the code block:
```javascript
return (window.ugma = ugma);
```
The right side if the statement is undefined, all we need to do to make it similar to jQuery is changing it to:
```javascript
define([
  './core',
  './document',
  //the rest of dependencies
], function(  /*core*/ ugma /*the rest of args*/) {
  return (window.ugma = ugma);
});
```
got it?

**Comment by Kflash** [comment]
@mehranhatami Go on. I will look closer when I'm back home

**Comment by mehranhatami** [comment]
@Kflash I will make the necessary changes on the `testing` branch, then hopefully there will be no issue in the testing scenario.

**Comment by Kflash** [comment]
@mehranhatami I changed the vars in main branch, take a look

**Comment by Kflash** [comment]
@mehranhatami I wrote a few tests, can you take a look? Everything works in my end.
It's limited what I can do, because I need HTML markup to do a lot of tests, and I'm not used to this setup.

Check my tests anyway.

**Comment by Kflash** [comment]
@mehranhatami I'm offline now, but check my tests in the main branch. I
assume you handle the rest now. And put up some HTML markup as well

**Comment by mehranhatami** [comment]
@KFlash  I'm not home at the moment, I'll check it out as soon as I am home.

**Comment by Kflash** [comment]
@mehranhatami ok. I created 15 various tests. Will check if I can put in
some html markup in the index

**Comment by Kflash** [comment]
@mehranhatami I wrote a few more tests, and added some basic HTML markup. You have to change all this ofc., so I stop now. And also I'm not so creative to come up with tests! I added **40**.

**Comment by Kflash** [comment]
@mehranhatami I added a few more test cases. Can you look, and give feedback? I had to stop working on this now, because you need to get the HTML markup right and nice looking. 

Waiting for your feedback!

**Comment by Kflash** [comment]
@mehranhatami I have now added 83 test cases randomly. But you set up a nice looking HTML markup now and split this tests into separate modules? And set up a test environment for events, manipulation etc?  Should also have added a benchmark on this?

**Comment by Kflash** [comment]
@mehranhatami when do you think we have a testing environment? ?

**Comment by mehranhatami** [comment]
@KFlash the point is we need to first decide if we are going to run the
tests only on the distro build of the Ugma as it is now, or we are willing
to setup a real testing environment to test the each module separately.
Your tests so far all only run on the distro, you could check it out on
index.html. and if we decide to setup the amd based solution to test
modules separately, it needs me to spend couple of days.

**Comment by Kflash** [comment]
@mehranhatami you go a head and set up a AMD environment

**Comment by Kflash** [comment]
@mehranhatami How long time you think  you would need to set ip a real testing environment to test eash module? AMD ?

**Comment by mehranhatami** [comment]
@KFlash all the steps I need to take in order to make all the modules
testable separately is totally clear. I have to start from the very first
module which is core.js and go through its dependencies and also
the dependencies of its dependencies and fix the dependency tree. But as
said it might take couple of days. I have already started the process in
testing branch.

**Comment by Kflash** [comment]
@mehranhatami Ok. And as I see it now ugma is feature complete, so there
will be no more dependencies to deal with. I consider however to merge a
few of them. Anyway. Could you send a email and let me know what you think
about ugma

**Comment by Kflash** [comment]
@mehranhatami Is it possible for you to run a separate test case for **Android**?? I did a major update of ugma, so it should now support Android from Gingerbread to Lollipop, but I need tests for it.

Do you have a Android device to test on?

**Comment by mehranhatami** [comment]
@KFlash to be honest I haven't worked on any web app for Android devices so
that I have no idea of its corner cases or its risks, so I'm not hundred
percent sure that I could be the right person for implementing it.

**Comment by Kflash** [comment]
@mehranhatami I think we can solve it easy. If you now finish AMD test
environment we just create a test module for android. And open it with a
android device. The test will run as normal. I can write those tests.

How is your test case progress?

**Comment by Kflash** [comment]
@mehranhatami For Android,  when you setting up the test cases. Check out this **jQuery issue** and implement / develop similar for ugma in the css module. https://github.com/jquery/jquery/pull/1842

You have to add this code same as you write tests, so you can test it.

You fix??

**Comment by Kflash** [comment]
@mehranhatami  Any progress on the test case scenario? I can't see any activity in the testing branch the last 3 days.

**Comment by Kflash** [comment]
@mehranhatami I repeat my question. How it goes with test cases? Are everything completed soon??

**Comment by mehranhatami** [comment]
@KFlash I'm busy during my weekdays in working hours, but considering the
time I could spend on it, mostly 2 hours a day, it takes couple of days to
fix all the AMD dependencies and setup the whole testing environment as I
said yesterday. So far the process has been a bit slow, but after fixing
the most used layers it gets faster.

**Comment by Kflash** [comment]
@mehranhatami OK. I will come back to this tomorrow. Anyways. A best test
scenario could be if you start to use ugma in your daily work. Can you
consider?

**Comment by Kflash** [comment]
@mehranhatami  Regarding the test cases. It's important that you use the test cases I already added into the new test solution. I just added testcases now for tabindex. Important.

You fix this, and when are you uploading?

**Comment by mehranhatami** [comment]
@KFlash actually this is how I am making sure when part of the testing
engine gets fixed, by running your test against it. I'm not sure but I
would probably be able to upload my output so far today, which is not
completed yet but it is working for couple of Ugma modules as said before,
each module separately.
Actually it is likely that I cannot answer my emails during the working
hours, any more so just beware and expect me to answer only each afternoon
of course in my local y time.

**Comment by Kflash** [comment]
@mehranhatami  **Important!!** I'm heavy testing accessor now on everything. It's important that we test it correctly. It's the heart and soul of everything. I'm using some jquery HTML markup, and it's a total mess. 

I HOPE you fix the HTML??

Anyways. Accessor handle props, attr, values, html, text etc. so it need heavy testing.

I'm uploading from time to time as soon as I know my tests works well, so you can copy & paste.

**Comment by Kflash** [comment]
@mehranhatami  I'm working on re-factoring the event management for ugma. When I re-write I also create some new tests for my changes, so use them in the test case.

**Comment by Kflash** [comment]
@mehranhatami When you test the event now, you see I fixed a few trigger() test cases. Use them. BUT you also need to add test cases for on(), once(), off().

According to the specs, I added now  **namespace**, you have to test for that too.

**Comment by Kflash** [comment]
@mehranhatami  Any progress on the test cases? I was expecting a upload yesterday.

**Comment by Kflash** [comment]
@mehranhatami I guess you are finished with the test cases now. When can I expect an upload from you?

**Comment by Kflash** [comment]
@mehranhatami When you do the test cases, can you check for IE 11 cross-browser issues? I see jQuery have fixed a few of them, but because of ugma is a different framework, we need to test different. 

Can you check and test this? And IF you find some issues, you fix?

I see example tagname SELECT can be issue or not? You check!!

**Comment by Kflash** [comment]
@mehranhatami Any progress on the test cases? I ask because you soon 6 days ago wrote you should fix the dependency tree and upload within 3 days. Seems like things turned around here, so I had to do your work as well.

Anyway. I mainly fixed the dependency tree now, just waiting for you upload.

**Comment by Kflash** [comment]
@mehranhatami Test cases? Where are they?

**Comment by Kflash** [comment]
@mehranhatami Test cases, what happen there? This should have been completed 5 days ago. Any progress????

**Comment by Kflash** [comment]
@mehranhatami Any progress? This should have been completed many days ago.
