### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by Kflash** [ugma/ugma#6]
@mehranhatami Run heavy testing on CSS module. I think we are supporting everything, but just to be sure. I just added **!important** support, and added test case for it. It's work!

If anything wrong with CSS, either fix it yourself or let me know.

**Comment by Kflash** [comment]
@mehranhatami Should we make this method global and hook it onto the ugma namespace?? **hyphenate()**

**Comment by mehranhatami** [comment]
@KFlash l feel it seems sometimes necessary for devs to have access to such
a function, my answer would be yes, hook it.


!a!

**Comment by Kflash** [comment]
@mehranhatami  It's hooked now as you see here. https://github.com/ugma/ugma/blob/master/dist/ugma.js#L2539
