### ISSUE TITLE
In progress: multiple documents

### ISSUE THREAD

**Issue by Kflash** [ugma/ugma#7]
@mehranhatami I'm now - after some thinking - introducing multiple documents. Each of this documents will have it's own subtree, and separated from each other. Also the methods are unique for each document.

**NOTE!!** Do not try this yet! Still work in progres...

I will illustrate. Today we have **ugma** as the javascript Framework, but what if we don't like it? Then we can do:

```javascript
// Create a new framwork
// NOTE! 'new' keyword need to be added
var Mehran =  new Document(document);
```

In this example, the framework are named **Mehran** and are working the same way as ugma. You can even hook it on the window object.

```javascript
window.Mehran = Mehran;
```
In the long run I see this as a better solution then multiple **ugma** on one site, that can cause conflicts.

We can also of cource create new Documents inside Documents, but not fully tested YET.

```javascript

ugma.on('click', ['target'], function(target) {
// Get it's own method separated from the rest of the world
var Mehran = new Document(target);
});

```

Further. I also added the option for creating a new Document subtree within ugma.

```javascript
ugma.constructor(document);
```
This method will create a new document separated from the other documents, with it's own functions. **NOTE!!** The methods for this document will not work on other documents.

@mehranhatami What I need your thougts about is if you are agree that we deprecate noConflict() method, and open up for multiple documents? And also any ideas on how to improve this?

Are we also going to restrict it to one **ugma** on each webpage,such as AngularJS do it?

**NOTE!!** This has nothing to do with the **shadows**

**Comment by Kflash** [comment]
@mehranhatami after some thinking I think multiple document only should allow multiple documents within ugma namespace. Agree? 

Still they get their own methods. Good news is that this is working today. And I added a test case for it.

Your thoughts?

**Comment by mehranhatami** [comment]
@KFlash I also think providing multiple documents this way could be a
valuable feature. But I think we need to provide devs with a good and
interactive documentation website, allowing them to change the code and
rerun it on the spot, otherwise they won't realize the value.

**Comment by Kflash** [comment]
@mehranhatami This is still work in progress, but the fact that we already
got 'shadows' - similar to shadow DOM - with it's own subtrees, and events
that are not floating into the main document tree, and it's own features
isolated from rest of the framework. I think messing around with the
namespace would be a bad idea - easy to use closures. So the solution will
be similar to shadow, except you are creating a new document and sharing
it's features.

You understand this?

**Comment by Kflash** [comment]
@mehranhatami Mission complete!! It's now possible to create new documents. And I added a new legacy method that accepts all **DOM nodes** and **document**.

The document will get it's own subtree.

A working example:

```javascript
   ugma.on('click', ['target'], function(target) {
   // target[0].ownerDocument is the same as document
     ugma.legacy(target[0].ownerDocument).css({'background-color': 'red'})
    });
```
Another example:

```javascript
    // Will get it's own set med functions for this document only
     ugma.legacy(document);
```
Further....

Ordinary DOM nodes can be attached and used the same way, but they will not get their own functions. But you can use chaining on them like this:

```javascript
var DOMnode = document.getElementById('test');
// Make it a ugma object, and gain chaining
ugma.legacy(DOMnode).css('width', '200em');
```
