### ISSUE TITLE
ugma whislist

### ISSUE THREAD

**Issue by Kflash** [ugma/ugma#9]
@mehranhatami  Let me know if you have a wishlist for ugma, what kind of features you hate in other libraries, and what you expect to find in libraries.

It can be as complicated you want, but if it's a feature / behaviour that are only bloating the code, I skip it.

I will implement it ASAP.

**Comment by Kflash** [comment]
@mehranhatami  Any ideas?

**Comment by mehranhatami** [comment]
@KFlash If you remember I had told you once about a SPA based on ExtJS, and
I've been thinking if I could find couple of forms in it to use Ugma in it.
I will et you know if I did.

**Comment by Kflash** [comment]
@mehranhatami Yep, I remember. The widgets you was creating the tree view etc. Ugma can be used to create such widgets in 5 minutes with minimal amount of code lines. 

But you mention forms? I assume *form* as in HTML markup *form*. Ugma works on forms, but no method for creating a queryString. Also solved this issues for **IE9** as you can see here:

https://github.com/ugma/ugma/blob/master/dist/ugma.js#L1592-L1608
